export const topics = [
  {
    topic: "Education",
    aspects: [
      "Traditional education vs. online learning",
      "Private vs. public schools",
      "Impact of AI and technology in classrooms",
      "Educational systems in different countries",
      "Role of teachers vs. self-learning",
      "Access to higher education",
      "Exam-oriented vs. creativity-focused education",
    ],
  },
  {
    topic: "Technology",
    aspects: [
      "Impact of smartphones on attention and focus",
      "Artificial Intelligence in daily life",
      "Social media and mental health",
      "Cybersecurity and data privacy",
      "Role of technology in education",
      "Wearable tech and health tracking",
      "Technology and human interaction",
    ],
  },
  {
    topic: "Environment",
    aspects: [
      "Global warming and extreme weather",
      "Urban pollution vs. rural sustainability",
      "Use of renewable energy (solar, wind, hydro)",
      "Climate change activism and awareness",
      "Plastic waste and ocean pollution",
      "Governmental vs. individual responsibility",
      "Environmental education for youth",
    ],
  },
  {
    topic: "Health",
    aspects: [
      "Mental health in modern society",
      "Benefits and risks of alternative medicine",
      "Obesity and fast food culture",
      "Universal healthcare vs. private systems",
      "Health effects of sedentary lifestyles",
      "Role of exercise in physical and mental health",
      "Vaccination debates and public health",
    ],
  },
  {
    topic: "Work & Career",
    aspects: [
      "Job satisfaction vs. salary",
      "Remote work and hybrid offices",
      "Changing careers and lifelong learning",
      "Gender equality in the workplace",
      "Workplace stress and burnout",
      "Internships and early career experience",
      "Entrepreneurship vs. working for a company",
    ],
  },
  {
    topic: "Culture",
    aspects: [
      "Preserving traditional customs",
      "Influence of Western culture",
      "Cultural identity in a globalized world",
      "Role of festivals and national holidays",
      "Language as a part of cultural heritage",
      "Intercultural communication challenges",
      "Art and literature as reflections of culture",
    ],
  },
  {
    topic: "Travel & Tourism",
    aspects: [
      "Eco-tourism and environmental impact",
      "Traveling as a way to learn about culture",
      "Influence of tourism on local communities",
      "Adventure vs. relaxation travel",
      "Benefits of studying or working abroad",
      "Role of travel agencies vs. self-planning",
      "Cultural shock and adaptation",
    ],
  },
  {
    topic: "Media & Communication",
    aspects: [
      "Freedom of the press vs. regulation",
      "Role of social media in shaping opinions",
      "Impact of fake news",
      "Decline of traditional print media",
      "Digital communication and relationships",
      "Celebrity culture and influence",
      "Use of memes and internet culture",
    ],
  },
  {
    topic: "Society & People",
    aspects: [
      "Aging population and care systems",
      "Urban-rural lifestyle differences",
      "Homelessness and social safety nets",
      "Volunteerism and civic duty",
      "Cultural norms and social taboos",
      "Peer pressure and youth behavior",
      "Generational conflict (youth vs. elderly)",
    ],
  },
  {
    topic: "Science & Innovation",
    aspects: [
      "Role of science in solving global problems",
      "Ethical concerns in genetic engineering",
      "Space exploration and colonization",
      "Green technologies and innovation",
      "STEM education and youth involvement",
      "Science vs. pseudoscience in media",
      "Impact of scientific discoveries on lifestyle",
    ],
  },
  {
    topic: "Art & Entertainment",
    aspects: [
      "Value of public funding for the arts",
      "Art as a form of political expression",
      "Role of museums and galleries",
      "Popularity of reality TV and its influence",
      "Streaming services vs. cinema experience",
      "Traditional vs. digital art",
      "Celebrity influence on young people",
    ],
  },
  {
    topic: "Sports & Leisure",
    aspects: [
      "Importance of physical fitness",
      "Team sports vs. individual sports",
      "Sports events and national pride",
      "Gender in professional sports",
      "E-sports and gaming as a profession",
      "Sports and discipline in youth",
      "Balance between leisure and productivity",
    ],
  },
  {
    topic: "Housing & Living",
    aspects: [
      "Living in cities vs. countryside",
      "High-rise apartments vs. houses",
      "Affordable housing issues",
      "Smart homes and modern living",
      "Green buildings and eco-design",
      "Homelessness and urban planning",
      "Cultural differences in living arrangements",
    ],
  },
  {
    topic: "Shopping & Consumption",
    aspects: [
      "Online vs. traditional shopping",
      "Consumerism and waste",
      "Brand loyalty and advertising",
      "Fast fashion and its impact",
      "Buying local vs. global products",
      "Impulse buying habits",
      "The psychology of shopping",
    ],
  },
  {
    topic: "Family & Relationships",
    aspects: [
      "Changing roles in the family",
      "Importance of family traditions",
      "Marriage and cohabitation",
      "Parenting styles and discipline",
      "Generational gaps",
      "Living with extended family",
      "Work-life balance and family time",
    ],
  },
];
